### ISSUE TITLE
[ombi] remove it

### ISSUE THREAD

**Issue by onedr0p** [k8s-at-home/container-images#28]
With conreq, petio and overseerr being released soon I don't see a need to support this image any more.

**Comment by bjw-s** [comment]
Removed with #29 
Do you want to leave the old images on Docker Hub or should we remove them too?

**Comment by onedr0p** [comment]
They can stay now that docker hub is doing their own mass purge on stale images 😅

**Comment by Ornias1993** [comment]
Between Ombi, Overseerr and conreq, what is the current "best" for handeling requests?
And why is Ombi removed while none of the alternatives got merged? Are their images already in a "best practice" state?

**Comment by bjw-s** [comment]
> Between Ombi, Overseerr and conreq, what is the current "best" for handeling requests?
> And why is Ombi removed while none of the alternatives got merged? Are their images already in a "best practice" state?

Please open a new discussion for the first part of your question (or join our Discord :P) instead of commenting on closed issues.

As for the second part: our goal is not to add / support every image or alternative that is out there. We add images along the way once we find there is a use for them. That is often loosely based on these criteria:
- Is there an official or de-facto official image available?
- If so, does it adhere to semver tags and is it multi-arch compatible?

If the answer to these questions is no, we discuss and consider adding it here.

**Comment by Ornias1993** [comment]
The first question was related: if ombi is still the de-facto standard, it's odd removing it just because there is a "new kid" on the block and that flows into the next question. It's one question really.

Thanks for the second half of the answer ofc, but that doesn't explain why it's removed. Afaik it's still the de-facto standard.

**Comment by bjw-s** [comment]
> it's odd removing it just because there is a "new kid" on the block

In the end, the reason is very simple: since the time we can spend on maintaining these images is limited and there are (in our opinion) better alternatives available we have chosen to drop support of Ombi in favour of other apps as mentioned in the original issue.

> Second:
> I already spend hours a day on Open Source projects. I expect documentation behind decisions on issues and PR's, not all sorts of forums or discords.

You are of course entitled to your opinion, but so are we. We have chosen to handle our support and questions either through our Discord (as we have indicated before) or through GitHub Discussions.

> Nor do I appreciate being spoken to this way just because an issue is closed, if you don't want responses disable them or block me from responding.

It was not my intention to offend, merely to redirect your remark to the correct location. A debate can be had about whether our communication styles are compatible, but that adds no value to this specific GitHub issue.

**Comment by onedr0p** [comment]
> Between Ombi, Overseerr and conreq, what is the current "best" for handeling requests?
> 
> And why is Ombi removed while none of the alternatives got merged? Are their images already in a "best practice" state?

Quite simple, we don't need to support images if they don't need to be. Which Ombi and the others currently fall into. The less to maintain on our end here, honestly  the better.
